# hexo-theme-miho
# https://github.com/wongminho/hexo-theme-miho

rss: /atom.xml

# Favicon of your site | 网站icon
favicon: /favicon.ico

# Header

# Keywords of your site | 网站关键字
keywords: SuperのLove,SuperのLove's blog
# Head headline | 头部标题
header_title: SuperのLove's blog
# Head description | 头部描述
header_description: 梦中做梦，做了个白日梦
# Link to your logo | logo地址
logo: images/mylogo.png
# Link to your banner_img | 首页banner图地址
banner_img: /images/BeJ.jpg
# Menu setting | 菜单设置
#  name:                  Font Awesome icon | Font Awesome 图标
#    title: Home          Title | 标题
#    url: //www.slblog.ga    Url, absolute or relative path | 链接，绝对或相对路径
#    target: true         Whether to jump out | 是否跳出
menu:
  home:
    title: 主页
    url: /
    target: false
  archive:
    title: Archives
    url: /archives
    target: false
  user:
    title: About
    url: /about
    target: false
  bullhorn:
    title: 公告
    url: /announcement
    target: false
  book:
    title: 分页
    url: /categories
    target: false
# Social setting, use to display social information | 社交设置，用来展示社交信息
#  name:                  Font Awesome icon | Font Awesome 图标
#    title: Home          Icon title | 图标标题
#    url: //www.slblog.ga/    Url, absolute or relative path | 链接，绝对或相对路径
#    target: true         Whether to jump out | 是否跳出
social:
  github:
    title: Github
    url: //github.com/Open-super
    target: true
  #qq: 3356620252
  #weixin:
  #snapchat:
  #telegram: SLQWQ
  #envelope-o:
  #facebook:
  #google: blackout33566@gmail.com
  #linkedin:

# Content

# Excerpt length | 摘录长度
excerpt_length: 190
# Excerpt link | 摘录链接
excerpt_link: more>>
# New window open link | 新窗口打开文章
open_new_link: false
# Article default cover picture，size：350*150 | 文章默认封面图，尺寸：350*150
cover_picture: images/banner.jpg
# Open background particles | 开启背景粒子
open_bg_particle: true
# Open animation in homepage and head | 开启主页及头部动画
open_animation: true

# Article

# Open toc | 是否开启toc
toc: true
# Open share | 是否开启分享
share: true

# Style customization | 样式定制
style:
  # Main color tone | 主色调
  main_color: '#0cc'

# Reward | 打赏

reward:
  # 0-close, 1-All articles are rewarding, 2-Article's md file has reward:true attribute, only reward
  # 0-关闭, 1-所有文章均有打赏, 2-文章的md文件里有reward:true属性，才有打赏
  status: 0
  # 标题
  title: 支持一下我吧，让我买个新域名。
  # 微信，关闭设为 false
  wechat: false
  # 支付宝，关闭设为 false
  alipay: false

# Comments | 评论

# 畅言，输入appid和appkey
changyan_appid: false
changyan_appkey: false
#来必力
livere: MTAyMC80ODgxNS8yNTMwOQ==
# 友言，输入id
youyan_id: false
# disqus
disqus: false
# gitment  https://github.com/imsun/gitment
gitment:
  owner: false   #你的 GitHub ID
  repo: ''   #存储评论的 repo
  client_id: '' #client ID
  client_secret: ''  #client secret

# Analytics | 分析
# 站长分析，输入站点id
cnzz_analytics: false
# 百度分析，输入key值
baidu_analytics: false
# google analytics | google分析
google_analytics: false

# Footer

# Access statistics | “不蒜子”访问量统计
access_counter:
  on: true
  site_uv: 来自不同地方的访客们啦~：
  site_pv: 访问量啦~：

# Copyright Information | 版权信息
copyright: 2020 失踪的SuperのLove 作者拥有版权，转载请注明出处! 未注明出处将追究法律责任。
